### ISSUE TITLE
RuntimeError ,Can not find any solutions online, How to fix it? :D

### ISSUE THREAD

**Issue by wjaycyf** [DongqiFu/SDG#1]
File "/home/aa/miniconda3/envs/torch_z36/lib/python3.6/site-packag
es/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aa/zxy/SDG-main/SDG-main/code/sdg/pytorch_code/utils
.py", line 56, in forward
    res = torch.sparse.mm(input, self.weight)
  File "/home/aa/miniconda3/envs/torch_z36/lib/python3.6/site-packag
es/torch/sparse/__init__.py", line 68, in mm
    return torch._sparse_mm(mat1, mat2)
**RuntimeError: CUDA error: kernel launch failure when calling `cusparse
Xcoo2csr(handle, coorowind, i_nnz, i_m, csrrowptr, CUSPARSE_INDEX_B
ASE_ZERO)`**

**Comment by DongqiFu** [comment]
Hi, What's your cuda version? My cuda is 10.1 and it works.
